### ISSUE TITLE
Installs fails. Missing dependency?

### ISSUE THREAD

**Issue by melezhik** [rbt/raku-Text-Diff#1]
Hi! FYI. Install fails.
http://repo.westus.cloudapp.azure.com/rakudist/reports/Text%3A%3ADiff/debian/1581032209.txt

HTH

Alexey

**Comment by rbt** [comment]
Thank-you. Failed to list a module in provides.

**Comment by melezhik** [comment]
looks good now. http://repo.westus.cloudapp.azure.com/rakudist/reports/Text%3A%3ADiff/debian/1581048411.txt
